use crate::{
    extractors::{
        ActionExtractor,
        CodeBlockExtractor,
        CommandExtractor,
        InstructionExtractor,
    },
    tokenizer::Tokenizer,
    types::ParsedResponse,
};

pub struct ParserCore {
    tokenizer: Tokenizer,
    code_blocks: CodeBlockExtractor,
    commands: CommandExtractor,
    instructions: InstructionExtractor,
    actions: ActionExtractor,
}

impl ParserCore {
    pub fn new() -> Self {
        Self {
            tokenizer: Tokenizer::new(),
            code_blocks: CodeBlockExtractor::new(),
            commands: CommandExtractor::new(),
            instructions: InstructionExtractor::new(),
            actions: ActionExtractor::new(),
        }
    }

    pub fn parse(&self, response: &str) -> ParsedResponse {
        let _tokens = self.tokenizer.tokenize(response);

        let blocks = self.code_blocks.extract(response);
        let commands = self.commands.extract(response);
        let instructions = self.instructions.extract(response);

        let mut actions = self.actions.extract(&instructions);

        // Attach code blocks to WriteFile actions
        let mut code_index = 0;

        for action in actions.iter_mut() {
            if action.kind == common::types::action::ActionKind::WriteFile {
                if let Some(block) = blocks.get(code_index) {
                    action.content = Some(block.clone());
                    code_index += 1;
                } else {
                    action.content = Some(String::from(
                        "// Generated by Universal AI Operator\n",
                    ));
                }
            }
        }

        let mut parsed = ParsedResponse::new(response);

        for block in blocks {
            parsed.add_code_block(block);
        }

        for command in commands {
            parsed.add_command(command.to_string());
        }

        for instruction in &instructions {
            parsed.add_file((*instruction).to_string());
        }

        for action in actions {
            parsed.add_action(action);
        }

        parsed
    }
}